name: Build Eaglercraft 1.21.4 WASM
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Eaglercraft 1.21
        run: |
          chmod +x gradlew
          # We are using the 'build' command the logs recommended
          ./gradlew build --no-daemon

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Eaglercraft-1.21-Client
          # This grabs the output from the standard Gradle build folder
          path: "**/build/libs/"
